#!/bin/bash
sudo yabai --load-sa

yabai -m config layout bsp
yabai -m config external_bar all
yabai -m config focus_follows_mouse off
yabai -m config window_opacity off

yabai -m config window_placement second_child
yabai -m config split_ratio 0.6

yabai -m config mouse_modifier ctrl

# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move
yabai -m config mouse_follows_focus on

yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

yabai -m rule --add app="^kitty$" manage=on space=1
yabai -m rule --add app="^python*$" manage=off

yabai -m config auto_balance off
