#!/bin/bash
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config layout bsp
yabai -m config external_bar all
yabai -m config focus_follows_mouse off
yabai -m config window_opacity off

yabai -m config window_placement second_child
yabai -m config split_ratio 0.5

yabai -m config mouse_modifier ctrl

# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move
yabai -m config mouse_follows_focus on

yabai -m config top_padding    0
yabai -m config bottom_padding 0
yabai -m config left_padding   0
yabai -m config right_padding  0
yabai -m config window_gap     0

yabai -m rule --add app="^python*$" manage=off

yabai -m rule --add app="^Ghostty$" manage=on space=1
yabai -m rule --add app="^Brave$" manage=on space=2
yabai -m rule --add app="^WhatsApp$" manage=on space=8

yabai -m config auto_balance off
